// constants/fieldNames.js
export const FIELD_NAMES = {
  PLANTADDRESS1: "PLANTADDRESS1",
  FRAME: "FRAME",
  PLANTNAME: "PLANTNAME",
  UNITNAME: "UNITNAME",
  SUBNAME: "SUBNAME",
  MACHINESN: "MACHINESN",
  CRM_PLANT_ID: "CRM_PLANT_ID",
  CRM_UNIT_ID: "CRM_UNIT_ID",
};
